name: Publish crates

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish leptris-descriptor
        run: cargo publish -p leptris-descriptor --token ${{ steps.auth.outputs.token }}
      - name: Publish leptris
        run: cargo publish -p leptris --token ${{ steps.auth.outputs.token }}
